### ISSUE TITLE
[ALL] 단풍톤 시연 및 발표 전 Todo

### ISSUE THREAD

**Issue by ryuwon-dev** [9oormthon-univ/2024_DANPOONG_TEAM_42_BE#27]
## 🚀 어떤 기능인가요?

> 단풍톤 시연 및 발표 전 해결해야할 Todo 또는 이슈에 대해 정리해두시면 됩니다!

## ✅  작업 상세 내용
> **Auth**
- [x] 카카오 로그인 전체적인 확인 필요 (프론트 요청)
> **User**
- [x] 휴대폰 인증 대기시간 확인 필요(프론트 요청) => 프론트 확인중
> **Payment** 
- [x] 결제 페이지 조회 커스텀 이미지 추가
> **Point**
- [x] #24 
- [x] #25
- [x] 스윕스톤 myPieceIds 타입 수정 (프론트 요청)
> **Store**

> **Global**
- [x] ~~Jwt Bearer은 달려 있는데 null 값일 경우 500 에러~~ ->  리팩토링 이슈으로 #17 

> **에러**
- [x] ~~User 삭제 안되는 이슈~~ -> 리팩토링 이슈으로 #17 

> **데이터**
- [x] 카드 데이터
- [x] 조각 데이터
- [x] 가게 데이터
- [x] 가게 리뷰
- [x] 가게 이미지
- [x] 데이터 백업

> **기타**
- [x] 백엔드 아키텍쳐 설계도 그리기 (발표용)
- [x] 백엔드 기술스택 적기 (발표용) => 디자인으로 넘김
- [x] ERD 시각화 (발표용)
- [x] #30
- [x] ~~Swagger 수정~~ -> 리팩토링 이슈으로 #17
